In [1]:
import numpy as np
import pandas as pd

filePath = "Z:\SEM5\Data-Analysis-main\winequality-red.csv"

In [28]:
# dataset = pd.read_csv("D:\\Settings\\winequality-red.csv")

wineData = np.genfromtxt(filePath,delimiter=";",skip_header = 1,dtype=np.float64)

print(wineData)


[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [3]:
print(f'The shape of the dataset is : {wineData.shape}')

The shape of the dataset is : (1599, 12)


In [4]:
#3rd row print

print(f'3rd row : \n{wineData[2]}')

#4th coloumn

print(f"4th coloumn : \n{wineData[:,3]}")


3rd row : 
[7.80e+00 7.60e-01 4.00e-02 2.30e+00 9.20e-02 1.50e+01 5.40e+01 9.97e-01
 3.26e+00 6.50e-01 9.80e+00 5.00e+00]
4th coloumn : 
[1.9 2.6 2.3 ... 2.3 2.  3.6]


In [5]:
#  first 3 ele of 4th coloumn

print(f" 4 col first 3 : \n{wineData[:3,4-1]}")

 4 col first 3 : 
[1.9 2.6 2.3]


In [6]:
#3rd col of each row

print(f'3rd Col : \n{wineData[:,3-1]}')

3rd Col : 
[0.   0.   0.04 ... 0.13 0.12 0.47]


In [7]:
#4th row

print(f"4th row : \n{wineData[4]}")

4th row : 
[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
  0.56    9.4     5.    ]


In [8]:
#wine 2,6 <-- 10

print(wineData[1])
wineData[2-1][6-1] = 10
print(wineData[1])


[ 7.8     0.88    0.      2.6     0.098  25.     67.      0.9968  3.2
  0.68    9.8     5.    ]
[ 7.8     0.88    0.      2.6     0.098  10.     67.      0.9968  3.2
  0.68    9.8     5.    ]


In [9]:
# slice <-- wine i, 10

slice_ = wineData[:,10]

print(slice_)

slice_[:] = 666

print(slice_)



[ 9.4  9.8  9.8 ... 11.  10.2 11. ]
[666. 666. 666. ... 666. 666. 666.]


In [10]:
# DISPLAY

print(wineData)

[[7.40e+00 7.00e-01 0.00e+00 ... 5.60e-01 6.66e+02 5.00e+00]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.80e-01 6.66e+02 5.00e+00]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.50e-01 6.66e+02 5.00e+00]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 7.50e-01 6.66e+02 6.00e+00]
 [5.90e+00 6.45e-01 1.20e-01 ... 7.10e-01 6.66e+02 5.00e+00]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.60e-01 6.66e+02 6.00e+00]]


In [11]:
print(f' DataType of the data set is {wineData.dtype}')

print(wineData)

wineData = wineData.astype(int)

print(wineData)

print(f' DataType of the data set is {wineData.dtype}')

 DataType of the data set is float64
[[7.40e+00 7.00e-01 0.00e+00 ... 5.60e-01 6.66e+02 5.00e+00]
 [7.80e+00 8.80e-01 0.00e+00 ... 6.80e-01 6.66e+02 5.00e+00]
 [7.80e+00 7.60e-01 4.00e-02 ... 6.50e-01 6.66e+02 5.00e+00]
 ...
 [6.30e+00 5.10e-01 1.30e-01 ... 7.50e-01 6.66e+02 6.00e+00]
 [5.90e+00 6.45e-01 1.20e-01 ... 7.10e-01 6.66e+02 5.00e+00]
 [6.00e+00 3.10e-01 4.70e-01 ... 6.60e-01 6.66e+02 6.00e+00]]
[[  7   0   0 ...   0 666   5]
 [  7   0   0 ...   0 666   5]
 [  7   0   0 ...   0 666   5]
 ...
 [  6   0   0 ...   0 666   6]
 [  5   0   0 ...   0 666   5]
 [  6   0   0 ...   0 666   6]]
 DataType of the data set is int32


In [12]:
#sum of all ele
print("sum of all :",np.sum(wineData))
#sum of coloumns
print("sum of col :",np.sum(wineData, axis = 0))
#sum of rows
print("sum of row :",np.sum(wineData,axis = 1))

sum of all : 1194489
sum of col : [  12589      24       1    3350       0   25367   74301      81    4770
      60 1064934    9012]
sum of row : [727 760 752 ... 752 757 744]


In [13]:
#quality <- quality + 10]
wineData[:,11]+=10
wineData[:,11]

array([15, 15, 15, ..., 16, 15, 16])

In [22]:
#quality <- quality + quality
print(wineData[:,11])

wineData[:,11]+=wineData[:,11]

print(wineData[:,11])



[5. 5. 5. ... 6. 5. 6.]
[10. 10. 10. ... 12. 10. 12.]


In [26]:
#quality X alchol
print(wineData[:10,-1]*wineData[:10,-2])
wineData[:,-1] = wineData[:,-1]*wineData[:,-2]

[ 94.   98.   98.  117.6  94.   94.   94.  140.  133.  105. ]


In [31]:
# which wines have a quality rating higher than 5.
wineData[np.where(wineData[:,-1]>5)]

array([[11.2 ,  0.28,  0.56, ...,  0.58,  9.8 ,  6.  ],
       [ 7.3 ,  0.65,  0.  , ...,  0.47, 10.  ,  7.  ],
       [ 7.8 ,  0.58,  0.02, ...,  0.57,  9.5 ,  7.  ],
       ...,
       [ 5.9 ,  0.55,  0.1 , ...,  0.76, 11.2 ,  6.  ],
       [ 6.3 ,  0.51,  0.13, ...,  0.75, 11.  ,  6.  ],
       [ 6.  ,  0.31,  0.47, ...,  0.66, 11.  ,  6.  ]])

In [46]:
#Check if any wines have a quality rating equal to 10.
if(np.where(wineData[:,-1]>=10)[0].size!=0):
    print("Wine with quality 10 exists")
else: print("Wine with quality of 10 doesn't exists")

Wine with quality of 10 doesn't exists


In [71]:
# Select rows in wines where the quality is over 7
wineData[np.where(wineData[:,-1]>=7)]

array([[ 7.3 ,  0.65,  0.  , ...,  0.47, 10.  ,  7.  ],
       [ 7.8 ,  0.58,  0.02, ...,  0.57,  9.5 ,  7.  ],
       [ 8.5 ,  0.28,  0.56, ...,  0.75, 10.5 ,  7.  ],
       ...,
       [ 7.4 ,  0.36,  0.3 , ...,  0.7 , 11.4 ,  8.  ],
       [ 7.  ,  0.56,  0.17, ...,  0.68, 10.55,  7.  ],
       [ 6.7 ,  0.32,  0.44, ...,  0.8 , 11.6 ,  7.  ]])

In [72]:
x = wineData[(wineData[:,-1]>=7)&(wineData[:,-2]>=10)]
x,x.size

(array([[ 7.3 ,  0.65,  0.  , ...,  0.47, 10.  ,  7.  ],
        [ 8.5 ,  0.28,  0.56, ...,  0.75, 10.5 ,  7.  ],
        [ 8.  ,  0.59,  0.16, ...,  0.92, 10.5 ,  7.  ],
        ...,
        [ 7.4 ,  0.36,  0.3 , ...,  0.7 , 11.4 ,  8.  ],
        [ 7.  ,  0.56,  0.17, ...,  0.68, 10.55,  7.  ],
        [ 6.7 ,  0.32,  0.44, ...,  0.8 , 11.6 ,  7.  ]]),
 2460)

In [76]:
print(wineData)
z = wineData.reshape((12,1599))
print(z)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
[[7.40000e+00 7.00000e-01 0.00000e+00 ... 6.60000e+00 5.00000e-01
  1.00000e-02]
 [1.50000e+00 6.00000e-02 1.70000e+01 ... 3.30000e+00 9.60000e-02
  2.60000e+01]
 [6.10000e+01 1.00025e+00 3.60000e+00 ... 4.20000e+01 9.96300e-01
  3.10000e+00]
 ...
 [2.30000e+00 7.60000e-02 2.30000e+01 ... 1.70000e+00 7.50000e-02
  6.00000e+00]
 [2.50000e+01 9.95810e-01 3.09000e+00 ... 5.30000e+01 9.95800e-01
  3.41000e+00]
 [6.70000e-01 9.70000e+00 5.00000e+00 ... 6.60000e-01 1.10000e+01
  6.00000e+00]]
